// ionic-react/src/tabs/resenas/lists/ResenasRecientes.tsx
import ResenaIndividual from '@/components/resenas/ResenaIndividual';
import { IonItem, IonList } from '@ionic/react';

const ResenasRecientes: React.FC = () => {
  return (
    <div className='my-6 w-full'>
      <h3 className='text-2xl font-medium text-zinc-800 dark:text-zinc-100'>Reseñas recientes</h3>
      <div className='flex h-full w-full flex-col'>
        <div className='group mt-6 h-56 w-full'>
          <IonList>
            <IonItem className='mt-4'>
              <ResenaIndividual
                rating={3.0}
                username='daniela.quinones'
                userImg='https://www.inf.ucv.cl/wp-content/uploads/2019/10/122139330_1301305493538238_2057443899688640217_n-1.jpg'
                obra={{ title: 'Obra de ejemplo', id: 1 }}
                review='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
              />
            </IonItem>
            <IonItem className='mt-4'>
              <ResenaIndividual
                rating={1.5}
                username='guillermo.cabrera'
                userImg='https://www.inf.ucv.cl/wp-content/uploads/2019/11/GuillermoCabreraG.jpg'
                obra={{ title: 'Obra de ejemplo', id: 1 }}
                review='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
              />
            </IonItem>
          </IonList>
        </div>
      </div>
    </div>
  );
};

export default ResenasRecientes;

// ionic-angular/src/app/home/resenas-recientes/resenas-recientes.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-resenas-recientes',
  templateUrl: './resenas-recientes.component.html',
})
export class ResenasRecientesComponent implements OnInit {
  resenasRecientes: Array<{
    username: string;
    userImg: string;
    rating: number;
    obra: { title: string; id: number };
    review: string;
  }> = [
    {
      username: 'claudio.cubillos',
      userImg:
        'https://www.inf.ucv.cl/wp-content/uploads/2019/11/ClaudioCubillosF.jpg',
      rating: 4.0,
      obra: {
        title: 'Obra de ejemplo',
        id: 1,
      },
      review:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      username: 'ricardo.soto',
      userImg:
        'https://www.inf.ucv.cl/wp-content/uploads/2019/11/RicardoSotoD-1.jpg',
      rating: 4.5,
      obra: {
        title: 'Obra de ejemplo',
        id: 1,
      },
      review:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      username: 'ivan.mercado',
      userImg:
        'https://www.inf.ucv.cl/wp-content/uploads/2019/11/IvanMercadoB.jpg',
      rating: 3.5,
      obra: {
        title: 'Obra de ejemplo',
        id: 1,
      },
      review:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      username: 'sandra.cano',
      userImg:
        'https://www.inf.ucv.cl/wp-content/uploads/2019/10/fotoSandraCano2-e1595970787778.png',
      rating: 5.0,
      obra: {
        title: 'Obra de ejemplo',
        id: 1,
      },
      review:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      username: 'ignacio.araya',
      userImg:
        'https://www.inf.ucv.cl/wp-content/uploads/2019/11/IgnacioArayaZ.jpg',
      rating: 2.5,
      obra: {
        title: 'Obra de ejemplo',
        id: 1,
      },
      review:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      username: 'wenceslao.palma',
      userImg:
        'https://www.inf.ucv.cl/wp-content/uploads/2019/11/WenceslaoPalmaM.jpg',
      rating: 4.5,
      obra: {
        title: 'Obra de ejemplo',
        id: 1,
      },
      review:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      username: 'daniela.quinones',
      userImg:
        'https://www.inf.ucv.cl/wp-content/uploads/2019/10/122139330_1301305493538238_2057443899688640217_n-1.jpg',
      rating: 3.0,
      obra: {
        title: 'Obra de ejemplo',
        id: 1,
      },
      review:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      username: 'guillermo.cabrera',
      userImg:
        'https://www.inf.ucv.cl/wp-content/uploads/2019/11/GuillermoCabreraG.jpg',
      rating: 1.5,
      obra: {
        title: 'Obra de ejemplo',
        id: 1,
      },
      review:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
  ];

  constructor() {}

  ngOnInit() {}
}

<ion-list>
  <ion-list-header>
    <h3 class="text-2xl font-medium text-zinc-800 dark:text-zinc-100">
      Reseñas recientes
    </h3>
  </ion-list-header>
  <ion-item *ngFor="let resena of resenasRecientes" class="mt-4">
    <app-resena-individual
      [username]="resena.username"
      [userImg]="resena.userImg"
      [rating]="resena.rating"
      [review]="resena.review"
      [obra]="resena.obra">
    </app-resena-individual>
  </ion-item>
</ion-list>
